--- 
addons: 
  apt: 
    packages: 
      - oracle-java8-installer
      - oracle-java8-set-default
jdk: 
  - oraclejdk8
services:
  - mysql
script: 
  - ./gradlew test
before_cache: 
  - "rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock"
  - "rm -fr $HOME/.gradle/caches/*/plugin-resolution/"
before_install: 
  - "chmod +x gradle/wrapper/gradle-wrapper.jar"
  - mysql -e 'CREATE DATABASE certificaten_test;'
cache: 
  directories: 
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
language: java
sudo: false

